/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/comp/Téléchargements/nim-0.13.0/lib' -o /home/comp/Dev/_lab/nim-hello/nimcache/hello_main.o /home/comp/Dev/_lab/nim-hello/nimcache/hello_main.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct WindowptrHEX3Aobjecttype109573 WindowptrHEX3Aobjecttype109573;
typedef struct RendererptrHEX3Aobjecttype109575 RendererptrHEX3Aobjecttype109575;
typedef struct Event109157 Event109157;
typedef struct Fpsmanager121406 Fpsmanager121406;
typedef N_CDECL_PTR(NI32, TY118966) (int flags);
typedef N_CDECL_PTR(WindowptrHEX3Aobjecttype109573*, TY119531) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(RendererptrHEX3Aobjecttype109575*, TY119006) (WindowptrHEX3Aobjecttype109573* window, int index, int flags);
typedef NU8 TY109344[52];
struct  Event109157  {
NI32 kind;
TY109344 padding;
};
struct  Fpsmanager121406  {
int framecount;
float rateticks;
int baseticks;
int lastticks;
int rate;
};
typedef N_CDECL_PTR(void, TY122402) (Fpsmanager121406* manager);
typedef N_CDECL_PTR(NI32, TY119763) (Event109157* event);
typedef N_CDECL_PTR(int, TY122411) (Fpsmanager121406* manager);
typedef N_CDECL_PTR(NI32, TY118818) (RendererptrHEX3Aobjecttype109575* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY119207) (RendererptrHEX3Aobjecttype109575* renderer);
typedef N_CDECL_PTR(void, TY119218) (RendererptrHEX3Aobjecttype109575* renderer);
typedef N_CDECL_PTR(int, TY122419) (Fpsmanager121406* manager);
typedef N_CDECL_PTR(void, TY118849) (RendererptrHEX3Aobjecttype109575* renderer);
typedef N_CDECL_PTR(void, TY119563) (WindowptrHEX3Aobjecttype109573* window);
struct  WindowptrHEX3Aobjecttype109573  {
char dummy;
};
struct  RendererptrHEX3Aobjecttype109575  {
char dummy;
};
N_NIMCALL(NIM_BOOL, tobool_109654)(NI32 some);
static N_INLINE(NF, HEX2F_88438)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, destroy_120134)(WindowptrHEX3Aobjecttype109573* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, mainInit000)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
extern TY118966 Dl_118965;
WindowptrHEX3Aobjecttype109573* window_123001;
RendererptrHEX3Aobjecttype109575* render_123002;
extern TY119531 Dl_119530;
extern TY119006 Dl_119005;
Event109157 evt_123009;
extern Event109157 defaultevent_120401;
NIM_BOOL rungame_123010;
Fpsmanager121406 fpsman_123011;
extern TY122402 Dl_122401;
extern TY119763 Dl_119762;
NF dt_123026;
extern TFrame* frameptr_19436;
extern TY122411 Dl_122410;
extern TY118818 Dl_118817;
extern TY119207 Dl_119206;
extern TY119218 Dl_119217;
extern TY122419 Dl_122418;
extern TY118849 Dl_118848;
extern TY119563 Dl_119562;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NF, HEX2F_88438)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(3120, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, destroy_120134)(WindowptrHEX3Aobjecttype109573* window) {
	nimfr("destroy", "sdl2.nim")
	nimln(1712, "sdl2.nim");
	Dl_119562(window);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_gfxDatInit000();
	mainDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	sdl2_gfxInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	mainInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, mainInit000)(void) {
	NI32 LOC1;
	NI32 LOC13;
	int LOC14;
	int LOC15;
	nimfr("main", "main.nim")
	nimln(4, "main.nim");
	LOC1 = 0;
	LOC1 = Dl_118965(((int) 65535));
	nimln(10, "main.nim");
	window_123001 = Dl_119530("SDL Skeleton", ((int) 100), ((int) 100), ((int) 640), ((int) 480), ((unsigned int) 4));
	nimln(11, "main.nim");
	render_123002 = Dl_119005(window_123001, ((int) -1), ((NI32) 14));
	nimln(14, "main.nim");
	evt_123009 = defaultevent_120401;
	nimln(15, "main.nim");
	rungame_123010 = NIM_TRUE;
	nimln(17, "main.nim");
	Dl_122401((&fpsman_123011));
	{
		nimln(19, "main.nim");
		while (1) {
			if (!rungame_123010) goto LA3;
			{
				nimln(20, "main.nim");
				while (1) {
					NI32 LOC6;
					NIM_BOOL LOC7;
					int LOC12;
					LOC6 = 0;
					LOC6 = Dl_119762((&evt_123009));
					LOC7 = 0;
					LOC7 = tobool_109654(LOC6);
					if (!LOC7) goto LA5;
					nimln(21, "main.nim");
					{
						if (!(evt_123009.kind == ((NI32) 256))) goto LA10;
						nimln(22, "main.nim");
						rungame_123010 = NIM_FALSE;
						nimln(23, "main.nim");
						goto LA4;
					}
					LA10: ;
					dt_123026 = 0;
					nimln(25, "main.nim");
					LOC12 = 0;
					LOC12 = Dl_122410((&fpsman_123011));
					dt_123026 = HEX2F_88438(((NI) (LOC12)), ((NI) 1000));
				} LA5: ;
			} LA4: ;
		} LA3: ;
	}
	nimln(27, "main.nim");
	LOC13 = 0;
	LOC13 = Dl_118817(render_123002, ((NU8) 0), ((NU8) 0), ((NU8) 0), ((NU8) 255));
	nimln(28, "main.nim");
	LOC14 = 0;
	LOC14 = Dl_119206(render_123002);
	nimln(30, "main.nim");
	Dl_119217(render_123002);
	nimln(31, "main.nim");
	LOC15 = 0;
	LOC15 = Dl_122418((&fpsman_123011));
	nimln(33, "main.nim");
	Dl_118848(render_123002);
	nimln(34, "main.nim");
	destroy_120134(window_123001);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

