/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/comp/Téléchargements/nim-0.13.0/lib' -o /home/comp/Dev/_lab/nim-hello/nimcache/sdl2_sdl2.o /home/comp/Dev/_lab/nim-hello/nimcache/sdl2_sdl2.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Event109157 Event109157;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct WindowptrHEX3Aobjecttype109573 WindowptrHEX3Aobjecttype109573;
typedef struct RendererptrHEX3Aobjecttype109575 RendererptrHEX3Aobjecttype109575;
typedef NU8 TY109344[52];
struct  Event109157  {
NI32 kind;
TY109344 padding;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY118966) (int flags);
typedef N_CDECL_PTR(WindowptrHEX3Aobjecttype109573*, TY119531) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(RendererptrHEX3Aobjecttype109575*, TY119006) (WindowptrHEX3Aobjecttype109573* window, int index, int flags);
typedef N_CDECL_PTR(NI32, TY119763) (Event109157* event);
typedef N_CDECL_PTR(NI32, TY118818) (RendererptrHEX3Aobjecttype109575* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY119207) (RendererptrHEX3Aobjecttype109575* renderer);
typedef N_CDECL_PTR(void, TY119218) (RendererptrHEX3Aobjecttype109575* renderer);
typedef N_CDECL_PTR(void, TY118849) (RendererptrHEX3Aobjecttype109575* renderer);
typedef N_CDECL_PTR(void, TY119563) (WindowptrHEX3Aobjecttype109573* window);
struct  WindowptrHEX3Aobjecttype109573  {
char dummy;
};
struct  RendererptrHEX3Aobjecttype109575  {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP184, "libSDL2.so", 10);
STRING_LITERAL(TMP185, "libSDL2.so", 10);
Event109157 defaultevent_120401;
static void* TMP183;
TY118966 Dl_118965;
TY119531 Dl_119530;
TY119006 Dl_119005;
extern TFrame* frameptr_19436;
TY119763 Dl_119762;
TY118818 Dl_118817;
TY119207 Dl_119206;
TY119218 Dl_119217;
TY118849 Dl_118848;
TY119563 Dl_119562;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(NIM_BOOL, tobool_109654)(NI32 some) {
	NIM_BOOL result;
	nimfr("toBool", "sdl2.nim")
	result = 0;
	nimln(325, "sdl2.nim");
	result = ((NIM_BOOL) (some));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void) {
	Event109157 LOC1;
	nimfr("sdl2", "sdl2.nim")
	nimln(1770, "sdl2.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.kind = ((NI32) 256);
	defaultevent_120401 = LOC1;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void) {
if (!((TMP183 = nimLoadLibrary((NimStringDesc*) &TMP184))
)) nimLoadLibraryError((NimStringDesc*) &TMP185);
	Dl_118965 = (TY118966) nimGetProcAddr(TMP183, "SDL_Init");
	Dl_119530 = (TY119531) nimGetProcAddr(TMP183, "SDL_CreateWindow");
	Dl_119005 = (TY119006) nimGetProcAddr(TMP183, "SDL_CreateRenderer");
	Dl_119762 = (TY119763) nimGetProcAddr(TMP183, "SDL_PollEvent");
	Dl_118817 = (TY118818) nimGetProcAddr(TMP183, "SDL_SetRenderDrawColor");
	Dl_119206 = (TY119207) nimGetProcAddr(TMP183, "SDL_RenderClear");
	Dl_119217 = (TY119218) nimGetProcAddr(TMP183, "SDL_RenderPresent");
	Dl_118848 = (TY118849) nimGetProcAddr(TMP183, "SDL_DestroyRenderer");
	Dl_119562 = (TY119563) nimGetProcAddr(TMP183, "SDL_DestroyWindow");
}

