/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/comp/Téléchargements/nim-0.13.0/lib' -o /home/comp/Dev/_lab/nim-hello/nimcache/sdl2_gfx.o /home/comp/Dev/_lab/nim-hello/nimcache/sdl2_gfx.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct RendererptrHEX3Aobjecttype109575 RendererptrHEX3Aobjecttype109575;
typedef struct Surface110209 Surface110209;
typedef struct Fpsmanager121406 Fpsmanager121406;
typedef struct TY15805 TY15805;
typedef struct Pixelformat110203 Pixelformat110203;
typedef struct Rect109267 Rect109267;
typedef struct BlitmapptrHEX3Aobjecttype110251 BlitmapptrHEX3Aobjecttype110251;
typedef struct Palette110201 Palette110201;
typedef struct Color110199 Color110199;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY121602) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NU32 color);
typedef N_CDECL_PTR(NI32, TY121608) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121617) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 x2, NI16 y, NU32 color);
typedef N_CDECL_PTR(NI32, TY121624) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 x2, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121634) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y1, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121641) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y1, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121651) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121659) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121670) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121679) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121691) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121699) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121710) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121719) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121731) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121739) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121750) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121758) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121769) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 width, NU32 color);
typedef N_CDECL_PTR(NI32, TY121778) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 width, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121790) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121797) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121807) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU32 color);
typedef N_CDECL_PTR(NI32, TY121816) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121828) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121835) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121845) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 r, NU32 color);
typedef N_CDECL_PTR(NI32, TY121852) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121862) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU32 color);
typedef N_CDECL_PTR(NI32, TY121870) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121881) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU32 color);
typedef N_CDECL_PTR(NI32, TY121889) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121900) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU32 color);
typedef N_CDECL_PTR(NI32, TY121908) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121919) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU32 color);
typedef N_CDECL_PTR(NI32, TY121928) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121940) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU32 color);
typedef N_CDECL_PTR(NI32, TY121949) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121961) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU32 color);
typedef N_CDECL_PTR(NI32, TY121971) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121984) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU32 color);
typedef N_CDECL_PTR(NI32, TY121994) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY122007) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU32 color);
typedef N_CDECL_PTR(NI32, TY122017) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY122030) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, NU32 color);
typedef N_CDECL_PTR(NI32, TY122039) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY122051) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, NU32 color);
typedef N_CDECL_PTR(NI32, TY122060) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY122072) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, NU32 color);
typedef N_CDECL_PTR(NI32, TY122081) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY122093) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, Surface110209* texture, int texturedx, int texturedy);
typedef N_CDECL_PTR(NI32, TY122104) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, int s, NU32 color);
typedef N_CDECL_PTR(NI32, TY122113) (RendererptrHEX3Aobjecttype109575* renderer, NI16* vx, NI16* vy, int n, int s, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(void, TY122125) (void* fontdata, NU32 cw, NU32 ch);
typedef N_CDECL_PTR(void, TY122130) (NU32 rotation);
typedef N_CDECL_PTR(NI32, TY122133) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NIM_CHAR c, NU32 color);
typedef N_CDECL_PTR(NI32, TY122140) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NIM_CHAR c, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY122150) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NCSTRING s, NU32 color);
typedef N_CDECL_PTR(NI32, TY122157) (RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NCSTRING s, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(Surface110209*, TY122202) (Surface110209* src, double angle, double zoom, int smooth);
typedef N_CDECL_PTR(Surface110209*, TY122208) (Surface110209* src, double angle, double zoomx, double zoomy, int smooth);
typedef N_CDECL_PTR(void, TY122215) (int width, int height, double angle, double zoom, int* dstwidth, int* dstheight);
typedef N_CDECL_PTR(void, TY122224) (int width, int height, double angle, double zoomx, double zoomy, int* dstwidth, int* dstheight);
typedef N_CDECL_PTR(Surface110209*, TY122234) (Surface110209* src, double zoomx, double zoomy, int smooth);
typedef N_CDECL_PTR(void, TY122240) (int width, int height, double zoomx, double zoomy, int* dstwidth, int* dstheight);
typedef N_CDECL_PTR(Surface110209*, TY122249) (Surface110209* src, int factorx, int factory);
typedef N_CDECL_PTR(Surface110209*, TY122254) (Surface110209* src, int numclockwiseturns);
typedef N_CDECL_PTR(void, TY122402) (Fpsmanager121406* manager);
typedef N_CDECL_PTR(NI32, TY122406) (Fpsmanager121406* manager, int rate);
typedef N_CDECL_PTR(int, TY122411) (Fpsmanager121406* manager);
typedef N_CDECL_PTR(int, TY122415) (Fpsmanager121406* manager);
typedef N_CDECL_PTR(int, TY122419) (Fpsmanager121406* manager);
struct  RendererptrHEX3Aobjecttype109575  {
char dummy;
};
struct Rect109267 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  Surface110209  {
NU32 flags;
Pixelformat110203* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lockdata;
Rect109267 cliprect;
BlitmapptrHEX3Aobjecttype110251* map;
int refcount;
};
struct  Fpsmanager121406  {
int framecount;
float rateticks;
int baseticks;
int lastticks;
int rate;
};
typedef NU8 TY110234[2];
struct  Pixelformat110203  {
NU32 format;
Palette110201* palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY110234 padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
Pixelformat110203* next;
};
struct  BlitmapptrHEX3Aobjecttype110251  {
char dummy;
};
struct  Palette110201  {
int ncolors;
Color110199* colors;
NU32 version;
int refcount;
};
struct Color110199 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct TY15805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(void, mlstringrgba_122422)(RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NimStringDesc* S, NU8 R, NU8 G, NU8 B, NU8 A, NI16 linespacing);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_80210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, mlstringrgba_122451)(RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, TY15805* S, NU8 R, NU8 G, NU8 B, NU8 A, NI16 linespacing);
STRING_LITERAL(TMP163, "libSDL2_gfx.so", 14);
STRING_LITERAL(TMP164, "libSDL2_gfx.so.0", 16);
STRING_LITERAL(TMP165, "libSDL2_gfx-2.0.so", 18);
STRING_LITERAL(TMP166, "libSDL2_gfx-2.0.so.0", 20);
STRING_LITERAL(TMP167, "libSDL2_gfx(|-2.0).so(|.0)", 26);
static void* TMP162;
TY121602 Dl_121601;
TY121608 Dl_121607;
TY121617 Dl_121616;
TY121624 Dl_121623;
TY121634 Dl_121633;
TY121641 Dl_121640;
TY121651 Dl_121650;
TY121659 Dl_121658;
TY121670 Dl_121669;
TY121679 Dl_121678;
TY121691 Dl_121690;
TY121699 Dl_121698;
TY121710 Dl_121709;
TY121719 Dl_121718;
TY121731 Dl_121730;
TY121739 Dl_121738;
TY121750 Dl_121749;
TY121758 Dl_121757;
TY121769 Dl_121768;
TY121778 Dl_121777;
TY121790 Dl_121789;
TY121797 Dl_121796;
TY121807 Dl_121806;
TY121816 Dl_121815;
TY121828 Dl_121827;
TY121835 Dl_121834;
TY121845 Dl_121844;
TY121852 Dl_121851;
TY121862 Dl_121861;
TY121870 Dl_121869;
TY121881 Dl_121880;
TY121889 Dl_121888;
TY121900 Dl_121899;
TY121908 Dl_121907;
TY121919 Dl_121918;
TY121928 Dl_121927;
TY121940 Dl_121939;
TY121949 Dl_121948;
TY121961 Dl_121960;
TY121971 Dl_121970;
TY121984 Dl_121983;
TY121994 Dl_121993;
TY122007 Dl_122006;
TY122017 Dl_122016;
TY122030 Dl_122029;
TY122039 Dl_122038;
TY122051 Dl_122050;
TY122060 Dl_122059;
TY122072 Dl_122071;
TY122081 Dl_122080;
TY122093 Dl_122092;
TY122104 Dl_122103;
TY122113 Dl_122112;
TY122125 Dl_122124;
TY122130 Dl_122129;
TY122133 Dl_122132;
TY122140 Dl_122139;
TY122150 Dl_122149;
TY122157 Dl_122156;
TY122202 Dl_122201;
TY122208 Dl_122207;
TY122215 Dl_122214;
TY122224 Dl_122223;
TY122234 Dl_122233;
TY122240 Dl_122239;
TY122249 Dl_122248;
TY122254 Dl_122253;
TY122402 Dl_122401;
TY122406 Dl_122405;
TY122411 Dl_122410;
TY122415 Dl_122414;
TY122419 Dl_122418;
extern TFrame* frameptr_19436;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(void, mlstringrgba_122422)(RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, NimStringDesc* S, NU8 R, NU8 G, NU8 B, NU8 A, NI16 linespacing) {
	NI ln;
	nimfr("mlStringRGBA", "gfx.nim")
	nimln(255, "gfx.nim");
	ln = ((NI) 0);
	{
		NimStringDesc* L_122434;
		NI first_122448;
		NI last_122450;
		L_122434 = 0;
		nimln(452, "strutils.nim");
		first_122448 = ((NI) 0);
		nimln(453, "strutils.nim");
		last_122450 = ((NI) 0);
		{
			nimln(454, "strutils.nim");
			while (1) {
				NI TMP169;
				NI TMP170;
				NI TMP171;
				NI TMP172;
				NI TMP173;
				NI32 LOC6;
				NI TMP174;
				{
					nimln(455, "strutils.nim");
					while (1) {
						NI TMP168;
						nimln(1104, "system.nim");
						if ((NU)(last_122450) > (NU)(S->Sup.len)) raiseIndexError();
						if (!!((((NU8)(S->data[last_122450])) == ((NU8)(0)) || ((NU8)(S->data[last_122450])) == ((NU8)(13)) || ((NU8)(S->data[last_122450])) == ((NU8)(10))))) goto LA5;
						nimln(455, "strutils.nim");
						TMP168 = addInt(last_122450, ((NI) 1));
						last_122450 = (NI)(TMP168);
					} LA5: ;
				}
				nimln(456, "strutils.nim");
				TMP169 = subInt(last_122450, ((NI) 1));
				L_122434 = copyStrLast(S, first_122448, (NI)(TMP169));
				nimln(257, "gfx.nim");
				TMP170 = mulInt(ln, ((NI) 8));
				TMP171 = addInt(y, ((NI16)chckRange((NI)(TMP170), ((NI16) -32768), ((NI16) 32767))));
				if (TMP171 < -32768 || TMP171 > 32767) raiseOverflow();
				TMP172 = mulInt(ln, ((NI) (linespacing)));
				TMP173 = addInt((NI16)(TMP171), ((NI16)chckRange((NI)(TMP172), ((NI16) -32768), ((NI16) 32767))));
				if (TMP173 < -32768 || TMP173 > 32767) raiseOverflow();
				LOC6 = 0;
				LOC6 = Dl_122156(renderer, x, (NI16)(TMP173), L_122434->data, R, G, B, A);
				nimln(258, "gfx.nim");
				TMP174 = addInt(ln, ((NI) 1));
				ln = (NI)(TMP174);
				nimln(458, "strutils.nim");
				{
					NI TMP175;
					if ((NU)(last_122450) > (NU)(S->Sup.len)) raiseIndexError();
					if (!((NU8)(S->data[last_122450]) == (NU8)(10))) goto LA9;
					TMP175 = addInt(last_122450, ((NI) 1));
					last_122450 = (NI)(TMP175);
				}
				goto LA7;
				LA9: ;
				{
					NI TMP176;
					nimln(459, "strutils.nim");
					if ((NU)(last_122450) > (NU)(S->Sup.len)) raiseIndexError();
					if (!((NU8)(S->data[last_122450]) == (NU8)(13))) goto LA12;
					nimln(460, "strutils.nim");
					TMP176 = addInt(last_122450, ((NI) 1));
					last_122450 = (NI)(TMP176);
					nimln(461, "strutils.nim");
					{
						NI TMP177;
						if ((NU)(last_122450) > (NU)(S->Sup.len)) raiseIndexError();
						if (!((NU8)(S->data[last_122450]) == (NU8)(10))) goto LA16;
						TMP177 = addInt(last_122450, ((NI) 1));
						last_122450 = (NI)(TMP177);
					}
					LA16: ;
				}
				goto LA7;
				LA12: ;
				{
					nimln(462, "strutils.nim");
					goto LA2;
				}
				LA7: ;
				nimln(463, "strutils.nim");
				first_122448 = last_122450;
			}
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, mlstringrgba_122451)(RendererptrHEX3Aobjecttype109575* renderer, NI16 x, NI16 y, TY15805* S, NU8 R, NU8 G, NU8 B, NU8 A, NI16 linespacing) {
	NI ln;
	nimfr("mlStringRGBA", "gfx.nim")
	nimln(260, "gfx.nim");
	ln = ((NI) 0);
	{
		nimln(261, "gfx.nim");
		while (1) {
			NI TMP178;
			NI TMP179;
			NI TMP180;
			NI TMP181;
			NI32 LOC3;
			NI TMP182;
			if (!(ln < (S ? S->Sup.len : 0))) goto LA2;
			nimln(262, "gfx.nim");
			TMP178 = mulInt(ln, ((NI) 8));
			TMP179 = mulInt(ln, ((NI) (linespacing)));
			TMP180 = addInt((NI)(TMP178), (NI)(TMP179));
			TMP181 = addInt(y, ((NI16)chckRange((NI)(TMP180), ((NI16) -32768), ((NI16) 32767))));
			if (TMP181 < -32768 || TMP181 > 32767) raiseOverflow();
			if ((NU)(ln) >= (NU)(S->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = Dl_122156(renderer, x, (NI16)(TMP181), S->data[ln]->data, R, G, B, A);
			nimln(263, "gfx.nim");
			TMP182 = addInt(ln, ((NI) 1));
			ln = (NI)(TMP182);
		} LA2: ;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxInit000)(void) {
	nimfr("gfx", "gfx.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_gfxDatInit000)(void) {
if (!((TMP162 = nimLoadLibrary((NimStringDesc*) &TMP163))
||(TMP162 = nimLoadLibrary((NimStringDesc*) &TMP164))
||(TMP162 = nimLoadLibrary((NimStringDesc*) &TMP165))
||(TMP162 = nimLoadLibrary((NimStringDesc*) &TMP166))
)) nimLoadLibraryError((NimStringDesc*) &TMP167);
	Dl_121601 = (TY121602) nimGetProcAddr(TMP162, "pixelColor");
	Dl_121607 = (TY121608) nimGetProcAddr(TMP162, "pixelRGBA");
	Dl_121616 = (TY121617) nimGetProcAddr(TMP162, "hlineColor");
	Dl_121623 = (TY121624) nimGetProcAddr(TMP162, "hlineRGBA");
	Dl_121633 = (TY121634) nimGetProcAddr(TMP162, "vlineColor");
	Dl_121640 = (TY121641) nimGetProcAddr(TMP162, "vlineRGBA");
	Dl_121650 = (TY121651) nimGetProcAddr(TMP162, "rectangleColor");
	Dl_121658 = (TY121659) nimGetProcAddr(TMP162, "rectangleRGBA");
	Dl_121669 = (TY121670) nimGetProcAddr(TMP162, "roundedRectangleColor");
	Dl_121678 = (TY121679) nimGetProcAddr(TMP162, "roundedRectangleRGBA");
	Dl_121690 = (TY121691) nimGetProcAddr(TMP162, "boxColor");
	Dl_121698 = (TY121699) nimGetProcAddr(TMP162, "boxRGBA");
	Dl_121709 = (TY121710) nimGetProcAddr(TMP162, "roundedBoxColor");
	Dl_121718 = (TY121719) nimGetProcAddr(TMP162, "roundedBoxRGBA");
	Dl_121730 = (TY121731) nimGetProcAddr(TMP162, "lineColor");
	Dl_121738 = (TY121739) nimGetProcAddr(TMP162, "lineRGBA");
	Dl_121749 = (TY121750) nimGetProcAddr(TMP162, "aalineColor");
	Dl_121757 = (TY121758) nimGetProcAddr(TMP162, "aalineRGBA");
	Dl_121768 = (TY121769) nimGetProcAddr(TMP162, "thickLineColor");
	Dl_121777 = (TY121778) nimGetProcAddr(TMP162, "thickLineRGBA");
	Dl_121789 = (TY121790) nimGetProcAddr(TMP162, "circleColor");
	Dl_121796 = (TY121797) nimGetProcAddr(TMP162, "circleRGBA");
	Dl_121806 = (TY121807) nimGetProcAddr(TMP162, "arcColor");
	Dl_121815 = (TY121816) nimGetProcAddr(TMP162, "arcRGBA");
	Dl_121827 = (TY121828) nimGetProcAddr(TMP162, "aacircleColor");
	Dl_121834 = (TY121835) nimGetProcAddr(TMP162, "aacircleRGBA");
	Dl_121844 = (TY121845) nimGetProcAddr(TMP162, "filledCircleColor");
	Dl_121851 = (TY121852) nimGetProcAddr(TMP162, "filledCircleRGBA");
	Dl_121861 = (TY121862) nimGetProcAddr(TMP162, "ellipseColor");
	Dl_121869 = (TY121870) nimGetProcAddr(TMP162, "ellipseRGBA");
	Dl_121880 = (TY121881) nimGetProcAddr(TMP162, "aaellipseColor");
	Dl_121888 = (TY121889) nimGetProcAddr(TMP162, "aaellipseRGBA");
	Dl_121899 = (TY121900) nimGetProcAddr(TMP162, "filledEllipseColor");
	Dl_121907 = (TY121908) nimGetProcAddr(TMP162, "filledEllipseRGBA");
	Dl_121918 = (TY121919) nimGetProcAddr(TMP162, "pieColor");
	Dl_121927 = (TY121928) nimGetProcAddr(TMP162, "pieRGBA");
	Dl_121939 = (TY121940) nimGetProcAddr(TMP162, "filledPieColor");
	Dl_121948 = (TY121949) nimGetProcAddr(TMP162, "filledPieRGBA");
	Dl_121960 = (TY121961) nimGetProcAddr(TMP162, "trigonColor");
	Dl_121970 = (TY121971) nimGetProcAddr(TMP162, "trigonRGBA");
	Dl_121983 = (TY121984) nimGetProcAddr(TMP162, "aatrigonColor");
	Dl_121993 = (TY121994) nimGetProcAddr(TMP162, "aatrigonRGBA");
	Dl_122006 = (TY122007) nimGetProcAddr(TMP162, "filledTrigonColor");
	Dl_122016 = (TY122017) nimGetProcAddr(TMP162, "filledTrigonRGBA");
	Dl_122029 = (TY122030) nimGetProcAddr(TMP162, "polygonColor");
	Dl_122038 = (TY122039) nimGetProcAddr(TMP162, "polygonRGBA");
	Dl_122050 = (TY122051) nimGetProcAddr(TMP162, "aapolygonColor");
	Dl_122059 = (TY122060) nimGetProcAddr(TMP162, "aapolygonRGBA");
	Dl_122071 = (TY122072) nimGetProcAddr(TMP162, "filledPolygonColor");
	Dl_122080 = (TY122081) nimGetProcAddr(TMP162, "filledPolygonRGBA");
	Dl_122092 = (TY122093) nimGetProcAddr(TMP162, "texturedPolygon");
	Dl_122103 = (TY122104) nimGetProcAddr(TMP162, "bezierColor");
	Dl_122112 = (TY122113) nimGetProcAddr(TMP162, "bezierRGBA");
	Dl_122124 = (TY122125) nimGetProcAddr(TMP162, "gfxPrimitivesSetFont");
	Dl_122129 = (TY122130) nimGetProcAddr(TMP162, "gfxPrimitivesSetFontRotation");
	Dl_122132 = (TY122133) nimGetProcAddr(TMP162, "characterColor");
	Dl_122139 = (TY122140) nimGetProcAddr(TMP162, "characterRGBA");
	Dl_122149 = (TY122150) nimGetProcAddr(TMP162, "stringColor");
	Dl_122156 = (TY122157) nimGetProcAddr(TMP162, "stringRGBA");
	Dl_122201 = (TY122202) nimGetProcAddr(TMP162, "rotozoomSurface");
	Dl_122207 = (TY122208) nimGetProcAddr(TMP162, "rotozoomSurfaceXY");
	Dl_122214 = (TY122215) nimGetProcAddr(TMP162, "rotozoomSurfaceSize");
	Dl_122223 = (TY122224) nimGetProcAddr(TMP162, "rotozoomSurfaceSizeXY");
	Dl_122233 = (TY122234) nimGetProcAddr(TMP162, "zoomSurface");
	Dl_122239 = (TY122240) nimGetProcAddr(TMP162, "zoomSurfaceSize");
	Dl_122248 = (TY122249) nimGetProcAddr(TMP162, "shrinkSurface");
	Dl_122253 = (TY122254) nimGetProcAddr(TMP162, "rotateSurface90Degrees");
	Dl_122401 = (TY122402) nimGetProcAddr(TMP162, "SDL_initFramerate");
	Dl_122405 = (TY122406) nimGetProcAddr(TMP162, "SDL_setFramerate");
	Dl_122410 = (TY122411) nimGetProcAddr(TMP162, "SDL_getFramerate");
	Dl_122414 = (TY122415) nimGetProcAddr(TMP162, "SDL_getFramecount");
	Dl_122418 = (TY122419) nimGetProcAddr(TMP162, "SDL_framerateDelay");
}

